config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # User can see all the lists
  get "lists", to: "lists#index"

  # User can create a new list
  get "lists/new", to: "lists#new", as: :new_list
  post "lists", to: "lists#create"

  # User can see the details of a given list and its name
  get "lists/:id", to: "lists#show", as: :list

  # User can add a new bookmark (movie/list pair) to an existing list
  # GET lists/:id/bookmarks/new
  # POST lists/:id/bookmarks
  resources :lists, only: [:show] do
    resources :bookmarks, only: [:new, :create]
  end

  get "bookmarks/:id", to: "bookmarks#show", as: :bookmark

  # User can delete a bookmark from a list
  # DELETE bookmarks/:id
  delete "bookmarks/:id", to: "bookmarks#destroy"

  # POST lists/:list_id/reviews (list_reviews)
  # GET lists/:list_id/new (new_list_review)
  resources :lists, only: [:show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true
  validates :title, :overview, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    # Need a 'list_id' to associate the bookmark with
    @list = List.find(params[:list_id])
    # Assign the bookmark instance's list attribute to @list
    @bookmark.list = @list

    @bookmark.save
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to list_path(@list), notice: 'List was successfully created'
    else
      render :new
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    # Raise
    @movies = @list.movies
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    # Need a 'list_id' to associate the review with
    @list = List.find(params[:list_id])
    # Assign the review instance's list attribute to @list
    @review.list = @list

    @review.save
    if @review.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/new.html.erb
<div class="container py-5">
  <div class="row d-flex justify-content-center">
    <div class="col-12 col-md-6">
      <!-- Form-->
      <div class="bg-white p-3 rounded shadow">
        <!-- Add a new bookmark -->
        <h2>Add a movie to your <%= @list.name %> list</h2>

        <%= simple_form_for([@list, @bookmark]) do |f| %>
          <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
          <%= f.association :movie, prompt: 'Select a movie' %>
          <%= f.submit "Submit", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navbar -->
    <%= render 'shared/navbar' %>
    <!-- Page Content -->
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path("cover.jpg") %>)">
  <div class="container">
    <h1>Save <strong>any kind</strong> of <strong>movies</strong></h1>
    <p>Categorize your favourite movies by their genres</p>
    <%= link_to 'New movie List', new_list_path, class: "btn btn-flat" %>
  </div>
</div>

<div class="container py-5"> <!-- container -->
  <div class="d-flex align-items-center justify-content-between mb-3"> <!-- bootstrap flex-box -->
      <h2>My Lists</h2>
      <div>
        <%= link_to 'New movie List', new_list_path, class: "btn btn-flat" %>
      </div>
  </div>
</div>

<!-- Movie list cards -->
<div class="container">
  <div class="row pb-5">
        <% @lists.each do |list| %>
          <div class="col-12 col-sm-6 col-md-4 mb-4">
            <%= link_to list_path(list), class: "text-decoration-none" do %>
              <% if list.photo.attached? %>
                <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, height: 300, width: 400, crop: :fill %>')">
                  <%= list.name %>
                </div>
              <% else %>
                <div class="card-category" data-aos="zoom-in" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path("list_background.jpg") %>)">
                  <%= list.name %>
                </div>
              <% end %>

            <% end %>
          </div>
        <% end %>
      </div>
  </div>
</div>

<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.name %></td>
        <td><%= link_to 'Show', list, class: "btn btn-success" %></td>
        <td><%= link_to 'Add Bookmark', new_list_bookmark_path(list), class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New List', new_list_path, class: "btn btn-primary" %>
-->

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row d-flex justify-content-center">
    <div class="col-12 col-md-6">
    <!-- Form -->
      <div class="bg-light p-3 rounded shadow">
        <h2>Create a new list</h2>

        <%= simple_form_for(@list) do |f| %>
          <%= f.input :name, placeholder: "Horror" %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Submit", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<!-- Banner -->
<div class="position-relative">
  <% if @list.photo.attached? %>
    <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill %>')">
      <h1><%= @list.name %></h1>
      <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
    </div>
  <% else %>
    <div class="card-category card-large" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path("list_background.jpg") %>)">
      <h1><%= @list.name %></h1>
      <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
    </div>
  <% end %>
</div>

<p id="notice"><%= notice %></p>

<div class="container mb-5">
  <!-- Add movies button -->
  <div class="d-flex justify-content-end mb-3">
    <%= link_to 'Add Bookmark', new_list_bookmark_path(@list), class: "btn btn-flat" %>
  </div>

  <div class="row my-2">
    <!-- Movie cards -->
    <% @movies.each do |movie| %>
      <!-- Find the bookmark that contains the list_id-of this list & movie_id of movie belonging to this list_id -->
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>

      <div class="col-12 col-sm-6 col-md-6 mb-4">
        <div class="card bg-white rounded shadow h-100 p-4">

          <div class="movie-info">
            <!-- Title -->
            <p><strong><%= movie.title %></strong></p>
            <!-- Image -->
            <%= image_tag movie.poster_url, alt: movie.title, class: "movie-img rounded-top" %>
            <!-- Movie overview -->
            <small class="text-muted"><%= movie.overview %></small>
          </div>

          <div class="bookmark-info d-flex justify-content-between pt-4">
            <!-- Bookmark comment -->
            <i class="fas fa-quote-left me-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
            <!-- Delete button -->
            <small>
              <%= link_to "Delete",
              bookmark_path(bookmark),
              method: :delete,
              data: { confirm: "Are you sure?" },
              class: "text-danger text-decoration-none" %>
            </small>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

<!--
<div>
  <% @reviews.each do |review| %>
    <%= review.comment %>
    <%= review.rating %>
  <% end %>
</div>
-->

<div class="container">
  <%= link_to 'Add a Review', new_list_review_path(@list), class: "btn btn-flat" %>
</div>

<!-- Rough working -->
<!-- Display the movies -->
<!--
<p>
  <strong>Movies:</strong>
  <% @movies.each do |movie| %>
    <div class="list-group-item">
      <strong>Title:</strong>
      <p><%= movie.title %></p>

      <strong>Overview:</strong>
      <p><%= movie.overview %></p>

      <% store_movie_id = movie.id %>
-->
      <!-- Display the 'comment' -->
      <!--
      <strong>Your bookmark:</strong>

      <% @bookmarks.each do |bookmark| %>
        <% if bookmark.movie_id == store_movie_id %>
          <p><%= bookmark.comment %></p>
        <% end %>

        <%= link_to "Delete",
            bookmark_path(bookmark),
            method: :delete,
            data: { confirm: "Are you sure?" } %>

      <% end %>

    </div>
  <% end %>
</p>

 <%= link_to 'Back', lists_path, class: "btn btn-primary" %>
 -->

app/views/reviews/new.html.erb
<div class="container py-5">
  <div class="row d-flex justify-content-center">
    <div class="col-12 col-md-6">
    <!-- Form -->
      <div class="bg-light p-3 rounded shadow">
        <h2>Create a new review</h2>

        <%= simple_form_for([@list, @review]) do |f| %>
          <%= f.input :comment, placeholder: "What do you think about this movie list?" %>
          <%= f.input :rating %>
          <%= f.submit "Submit", class: "btn btn-flat" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <!-- Popcorn logo -->
    <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "popcorn.png", alt: "logo", class: "logo" %>
    <% end %>

    <!-- Hamburger icon (small screens) -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Nav tabs -->
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to 'My Lists', lists_path, class: "nav-link active" %>
        <%= link_to 'New List', new_list_path, class: "nav-link" %>
      </div>
    </div>
  </div>
</nav>